drop table if exists public.movimiento_inventario cascade;
drop table if exists public.producto cascade;

create table public.producto (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  categoria text not null,
  stock numeric(12,2) not null default 0,
  minimo numeric(12,2) not null default 0,
  unidad text not null default 'unidad',
  costo_unitario numeric(12,2),
  precio_compra numeric(12,2),
  precio_venta numeric(12,2),
  estado text not null default 'normal',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.movimiento_inventario (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.producto (id) on delete cascade,
  tipo text not null,
  cantidad numeric(12,2) not null,
  motivo text,
  usuario text,
  created_at timestamptz not null default now()
);

create index idx_movimiento_inventario_producto_id on public.movimiento_inventario (producto_id);
create index idx_movimiento_inventario_created_at on public.movimiento_inventario (created_at desc);
create index idx_producto_categoria on public.producto (categoria);
create index idx_producto_estado on public.producto (estado);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_producto_updated_at
before update on public.producto
for each row
execute function public.set_updated_at();

alter table public.producto enable row level security;
alter table public.movimiento_inventario enable row level security;

create policy "producto_select_authenticated"
  on public.producto
  for select
  to authenticated
  using (true);

create policy "movimiento_inventario_select_authenticated"
  on public.movimiento_inventario
  for select
  to authenticated
  using (true);
