-- Crear tabla receta
create table if not exists public.receta (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  categoria text not null default 'Bebidas',
  presentacion text,
  costo_total numeric(12,2) default 0,
  precio_sugerido numeric(12,2) default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Crear tabla ingrediente_receta
create table if not exists public.ingrediente_receta (
  id bigint generated by default as identity primary key,
  receta_id bigint not null references public.receta(id) on delete cascade,
  nombre text not null,
  cantidad numeric(12,2) not null,
  unidad text not null,
  costo_unitario numeric(12,2),
  created_at timestamptz not null default now()
);

-- Crear tabla plan_produccion
create table if not exists public.plan_produccion (
  id bigint generated by default as identity primary key,
  receta_id bigint not null references public.receta(id) on delete cascade,
  cantidad_planificada numeric(12,2) not null,
  demanda_proyectada numeric(12,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Crear tabla produccion
create table if not exists public.produccion (
  id bigint generated by default as identity primary key,
  receta_id bigint not null references public.receta(id) on delete cascade,
  cantidad numeric(12,2) not null,
  usuario text,
  lote text unique,
  created_at timestamptz not null default now()
);

-- Índices para búsquedas
create index if not exists idx_receta_categoria on public.receta(categoria);
create index if not exists idx_ingrediente_receta_id on public.ingrediente_receta(receta_id);
create index if not exists idx_plan_produccion_receta_id on public.plan_produccion(receta_id);
create index if not exists idx_produccion_receta_id on public.produccion(receta_id);
create index if not exists idx_produccion_lote on public.produccion(lote);
