alter table if exists public.ingrediente_receta
  add column if not exists producto_id bigint references public.producto(id);

create table if not exists public.venta_pos (
  id bigint generated by default as identity primary key,
  ticket text not null unique,
  cliente text,
  metodo_pago text not null default 'Efectivo',
  subtotal numeric(12,2) not null default 0,
  iva numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  usuario text,
  necesita_factura boolean default false,
  nit text,
  nombre_cliente text,
  numero_telefono text,
  created_at timestamptz not null default now()
);

create table if not exists public.venta_pos_detalle (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.venta_pos(id) on delete cascade,
  receta_id bigint not null references public.receta(id),
  cantidad numeric(12,2) not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_ingrediente_receta_producto_id on public.ingrediente_receta(producto_id);
create index if not exists idx_venta_pos_created_at on public.venta_pos(created_at desc);
create index if not exists idx_venta_pos_detalle_venta_id on public.venta_pos_detalle(venta_id);

drop function if exists public.registrar_venta_pos_consumo_directo(jsonb, text, text, text, boolean, text, text, text);
drop function if exists public.registrar_venta_pos_consumo_directo(text, jsonb, text, boolean, text, text, text, text);

create or replace function public.registrar_venta_pos_consumo_directo(
  p_cliente text default null,
  p_items jsonb default null,
  p_metodo_pago text default 'Efectivo',
  p_necesita_factura boolean default false,
  p_nit text default null,
  p_nombre_cliente text default null,
  p_numero_telefono text default null,
  p_usuario text default null
)
returns public.venta_pos
language plpgsql
as $$
declare
  v_venta public.venta_pos%rowtype;
  v_ticket text;
  v_subtotal numeric(12,2);
  v_iva numeric(12,2);
  v_total numeric(12,2);
  v_item record;
  v_req record;
  v_producto public.producto%rowtype;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La venta debe incluir al menos un producto.';
  end if;

  for v_item in
    select *
    from jsonb_to_recordset(p_items) as item(
      receta_id bigint,
      cantidad numeric,
      precio_unitario numeric
    )
  loop
    if v_item.receta_id is null then
      raise exception 'Todos los productos de venta deben tener receta.';
    end if;

    if v_item.cantidad is null or v_item.cantidad <= 0 then
      raise exception 'La cantidad vendida debe ser mayor a 0.';
    end if;

    if not exists (select 1 from public.receta where id = v_item.receta_id) then
      raise exception 'No se encontró una receta de la venta.';
    end if;

    if not exists (select 1 from public.ingrediente_receta where receta_id = v_item.receta_id) then
      raise exception 'La receta no tiene BOM definido.';
    end if;

    if exists (
      select 1
      from public.ingrediente_receta
      where receta_id = v_item.receta_id
        and producto_id is null
    ) then
      raise exception 'Todos los ingredientes del BOM deben estar vinculados a un producto de inventario.';
    end if;
  end loop;

  for v_req in
    with items as (
      select *
      from jsonb_to_recordset(p_items) as item(
        receta_id bigint,
        cantidad numeric,
        precio_unitario numeric
      )
    )
    select
      ing.producto_id,
      sum(ing.cantidad * items.cantidad)::numeric(12,2) as cantidad_requerida
    from items
    join public.ingrediente_receta ing on ing.receta_id = items.receta_id
    group by ing.producto_id
  loop
    select *
    into v_producto
    from public.producto
    where id = v_req.producto_id
    for update;

    if not found then
      raise exception 'No se encontró un insumo de inventario vinculado al BOM.';
    end if;

    if v_producto.stock < v_req.cantidad_requerida then
      raise exception 'Inventario insuficiente para %. Disponible: %, requerido: %.',
        v_producto.nombre,
        v_producto.stock,
        v_req.cantidad_requerida;
    end if;
  end loop;

  select
    coalesce(sum(coalesce(precio_unitario, 0) * cantidad), 0)::numeric(12,2)
  into v_subtotal
  from jsonb_to_recordset(p_items) as item(
    receta_id bigint,
    cantidad numeric,
    precio_unitario numeric
  );

  v_iva := round(v_subtotal * 0.12, 2);
  v_total := v_subtotal + v_iva;
  v_ticket := 'TKT-' || to_char(now(), 'YYYYMMDDHH24MISS') || '-' || floor(random() * 1000)::int;

  insert into public.venta_pos (
    ticket,
    cliente,
    metodo_pago,
    subtotal,
    iva,
    total,
    usuario,
    necesita_factura,
    nit,
    nombre_cliente,
    numero_telefono
  )
  values (
    v_ticket,
    nullif(btrim(coalesce(p_cliente, '')), ''),
    coalesce(nullif(btrim(p_metodo_pago), ''), 'Efectivo'),
    v_subtotal,
    v_iva,
    v_total,
    nullif(btrim(coalesce(p_usuario, '')), ''),
    coalesce(p_necesita_factura, false),
    nullif(btrim(coalesce(p_nit, '')), ''),
    nullif(btrim(coalesce(p_nombre_cliente, '')), ''),
    nullif(btrim(coalesce(p_numero_telefono, '')), '')
  )
  returning * into v_venta;

  insert into public.venta_pos_detalle (
    venta_id,
    receta_id,
    cantidad,
    precio_unitario,
    total
  )
  select
    v_venta.id,
    item.receta_id,
    item.cantidad,
    coalesce(item.precio_unitario, 0),
    coalesce(item.precio_unitario, 0) * item.cantidad
  from jsonb_to_recordset(p_items) as item(
    receta_id bigint,
    cantidad numeric,
    precio_unitario numeric
  );

  for v_req in
    with items as (
      select *
      from jsonb_to_recordset(p_items) as item(
        receta_id bigint,
        cantidad numeric,
        precio_unitario numeric
      )
    )
    select
      ing.producto_id,
      sum(ing.cantidad * items.cantidad)::numeric(12,2) as cantidad_requerida
    from items
    join public.ingrediente_receta ing on ing.receta_id = items.receta_id
    group by ing.producto_id
  loop
    update public.producto
    set stock = stock - v_req.cantidad_requerida,
        updated_at = now()
    where id = v_req.producto_id;

    insert into public.movimiento_inventario (
      producto_id,
      tipo,
      cantidad,
      cantidad_compra,
      motivo,
      usuario
    )
    values (
      v_req.producto_id,
      'Salida',
      v_req.cantidad_requerida,
      v_req.cantidad_requerida,
      'Venta POS ' || v_venta.ticket,
      nullif(btrim(coalesce(p_usuario, '')), '')
    );
  end loop;

  return v_venta;
end;
$$;
