-- Catálogo de tablas administrables desde el ERP

create table if not exists public.tabla_estructura (
  id bigint generated by default as identity primary key,
  nombre_visible text not null,
  nombre_interno text not null unique,
  descripcion text,
  modulo text not null,
  es_sistema boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campo_estructura (
  id bigint generated by default as identity primary key,
  tabla_id bigint not null references public.tabla_estructura(id) on delete cascade,
  nombre text not null,
  tipo_dato text not null,
  descripcion text,
  requerido boolean not null default false,
  unico boolean not null default false,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  unique (tabla_id, nombre)
);

create index if not exists idx_tabla_estructura_modulo on public.tabla_estructura(modulo);
create index if not exists idx_campo_estructura_tabla_id on public.campo_estructura(tabla_id);

create or replace function public.estructura_tipo_sql(p_tipo text)
returns text
language plpgsql
immutable
as $$
begin
  case lower(btrim(coalesce(p_tipo, '')))
    when 'text' then
      return 'text';
    when 'integer' then
      return 'integer';
    when 'bigint' then
      return 'bigint';
    when 'numeric' then
      return 'numeric(12,2)';
    when 'boolean' then
      return 'boolean';
    when 'date' then
      return 'date';
    when 'timestamp' then
      return 'timestamptz';
    else
      raise exception 'Tipo de dato no soportado: %', p_tipo;
  end case;
end;
$$;

create or replace function public.crear_tabla_estructura(
  p_nombre_interno text,
  p_nombre_visible text,
  p_modulo text,
  p_descripcion text default null,
  p_campos jsonb default '[]'::jsonb
)
returns public.tabla_estructura
language plpgsql
as $$
declare
  v_nombre_interno text := lower(btrim(coalesce(p_nombre_interno, '')));
  v_nombre_visible text := btrim(coalesce(p_nombre_visible, ''));
  v_modulo text := btrim(coalesce(p_modulo, ''));
  v_descripcion text := nullif(btrim(coalesce(p_descripcion, '')), '');
  v_tabla public.tabla_estructura%rowtype;
  v_campo record;
  v_columna_defs text[] := array['id bigint generated by default as identity primary key'];
  v_total_campos integer := 0;
  v_nombre_normalizado text;
  v_tipo_sql text;
begin
  if v_nombre_interno = '' or v_nombre_visible = '' or v_modulo = '' then
    raise exception 'nombre_interno, nombre_visible y modulo son obligatorios.';
  end if;

  if v_nombre_interno !~ '^[a-z_][a-z0-9_]*$' then
    raise exception 'El nombre interno debe usar minúsculas, números y guiones bajos.';
  end if;

  if jsonb_typeof(p_campos) is distinct from 'array' then
    raise exception 'Los campos deben enviarse como una lista.';
  end if;

  if jsonb_array_length(p_campos) = 0 then
    raise exception 'Debe agregar al menos un campo.';
  end if;

  if exists (
    select 1
    from public.tabla_estructura
    where nombre_interno = v_nombre_interno
  ) or exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = v_nombre_interno
  ) then
    raise exception 'El nombre interno ya existe.';
  end if;

  if exists (
    select 1
    from (
      select lower(btrim(coalesce(elem->>'nombre', ''))) as nombre_normalizado,
             count(*) as total
      from jsonb_array_elements(p_campos) as elem
      group by 1
      having count(*) > 1
    ) duplicados
  ) then
    raise exception 'No se permiten nombres de campos duplicados.';
  end if;

  insert into public.tabla_estructura (
    nombre_visible,
    nombre_interno,
    descripcion,
    modulo,
    es_sistema
  )
  values (
    v_nombre_visible,
    v_nombre_interno,
    v_descripcion,
    v_modulo,
    false
  )
  returning * into v_tabla;

  for v_campo in
    select
      lower(btrim(coalesce(elem->>'nombre', ''))) as nombre,
      coalesce(elem->>'tipoDato', elem->>'tipo_dato') as tipo_dato,
      nullif(btrim(coalesce(elem->>'descripcion', '')), '') as descripcion,
      coalesce((elem->>'requerido')::boolean, false) as requerido,
      coalesce((elem->>'unico')::boolean, false) as unico,
      row_number() over () as orden
    from jsonb_array_elements(p_campos) as elem
  loop
    if v_campo.nombre = '' then
      raise exception 'Todos los campos deben tener nombre.';
    end if;

    if v_campo.nombre !~ '^[a-z_][a-z0-9_]*$' then
      raise exception 'El nombre del campo % no es válido.', v_campo.nombre;
    end if;

    v_tipo_sql := public.estructura_tipo_sql(v_campo.tipo_dato);
    v_columna_defs := array_append(
      v_columna_defs,
      format(
        '%I %s%s%s',
        v_campo.nombre,
        v_tipo_sql,
        case when v_campo.requerido then ' not null' else '' end,
        case when v_campo.unico then ' unique' else '' end
      )
    );
    v_total_campos := v_total_campos + 1;
  end loop;

  if v_total_campos = 0 then
    raise exception 'Debe agregar al menos un campo válido.';
  end if;

  execute format(
    'create table public.%I (%s)',
    v_nombre_interno,
    array_to_string(v_columna_defs, ', ')
  );

  for v_campo in
    select
      lower(btrim(coalesce(elem->>'nombre', ''))) as nombre,
      coalesce(elem->>'tipoDato', elem->>'tipo_dato') as tipo_dato,
      nullif(btrim(coalesce(elem->>'descripcion', '')), '') as descripcion,
      coalesce((elem->>'requerido')::boolean, false) as requerido,
      coalesce((elem->>'unico')::boolean, false) as unico,
      row_number() over () as orden
    from jsonb_array_elements(p_campos) as elem
  loop
    insert into public.campo_estructura (
      tabla_id,
      nombre,
      tipo_dato,
      descripcion,
      requerido,
      unico,
      orden
    )
    values (
      v_tabla.id,
      v_campo.nombre,
      lower(btrim(coalesce(v_campo.tipo_dato, 'text'))),
      v_campo.descripcion,
      v_campo.requerido,
      v_campo.unico,
      v_campo.orden
    );
  end loop;

  insert into public.campo_estructura (
    tabla_id,
    nombre,
    tipo_dato,
    descripcion,
    requerido,
    unico,
    orden
  )
  values (
    v_tabla.id,
    'id',
    'bigint',
    'Clave primaria',
    true,
    true,
    0
  );

  return v_tabla;
end;
$$;

create or replace function public.eliminar_tabla_estructura(p_tabla_id bigint)
returns void
language plpgsql
as $$
declare
  v_tabla public.tabla_estructura%rowtype;
begin
  select *
  into v_tabla
  from public.tabla_estructura
  where id = p_tabla_id;

  if not found then
    raise exception 'No se encontró la tabla solicitada.';
  end if;

  if v_tabla.es_sistema then
    raise exception 'No se pueden eliminar tablas del sistema.';
  end if;

  execute format('drop table if exists public.%I cascade', v_tabla.nombre_interno);

  delete from public.tabla_estructura
  where id = v_tabla.id;
end;
$$;

do $$
declare
  v_tabla record;
  v_tabla_id bigint;
begin
  for v_tabla in
    select * from (values
      ('profiles', 'Perfiles', 'Seguridad y Acceso', 'Usuarios, roles y estados de acceso'),
      ('producto', 'Productos', 'Inventarios', 'Materias primas, suministros y demás insumos'),
      ('movimiento_inventario', 'Movimientos de Inventario', 'Inventarios', 'Entradas, salidas y mermas de bodega'),
      ('receta', 'Recetas', 'Producción y Recetas', 'Catálogo de recetas de venta'),
      ('ingrediente_receta', 'Ingredientes de Receta', 'Producción y Recetas', 'BOM de cada receta'),
      ('plan_produccion', 'Planes de Producción', 'Producción y Recetas', 'Planeación de lotes de producción'),
      ('produccion', 'Producciones', 'Producción y Recetas', 'Registro de lotes producidos'),
      ('venta_pos', 'Ventas POS', 'Punto de Venta', 'Cabecera de ventas registradas en caja'),
      ('venta_pos_detalle', 'Detalle de Ventas POS', 'Punto de Venta', 'Detalle de productos vendidos en POS'),
      ('weather_history', 'Historial Climático', 'IA Predictiva', 'Datos históricos de clima para pronóstico')
    ) as seed(nombre_interno, nombre_visible, modulo, descripcion)
  loop
    insert into public.tabla_estructura (
      nombre_visible,
      nombre_interno,
      descripcion,
      modulo,
      es_sistema
    )
    values (
      v_tabla.nombre_visible,
      v_tabla.nombre_interno,
      v_tabla.descripcion,
      v_tabla.modulo,
      true
    )
    on conflict (nombre_interno) do update
      set nombre_visible = excluded.nombre_visible,
          descripcion = excluded.descripcion,
          modulo = excluded.modulo,
          es_sistema = true,
          updated_at = now()
    returning id into v_tabla_id;

    delete from public.campo_estructura
    where tabla_id = v_tabla_id;

    insert into public.campo_estructura (
      tabla_id,
      nombre,
      tipo_dato,
      descripcion,
      requerido,
      unico,
      orden
    )
    select
      v_tabla_id,
      c.column_name,
      c.data_type,
      null,
      c.is_nullable = 'NO',
      c.column_name = 'id',
      c.ordinal_position
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.table_name = v_tabla.nombre_interno
    order by c.ordinal_position;
  end loop;
end $$;