-- Configuracion general del sistema ERP

create table if not exists public.config_empresa (
  id integer primary key default 1,
  nombre_empresa text not null,
  nit text not null,
  direccion text not null,
  telefono text not null,
  correo text not null,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.config_impuestos (
  id integer primary key default 1,
  iva_activo boolean not null default true,
  iva_porcentaje numeric(5,2) not null default 12,
  otros_impuestos jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.config_notificaciones (
  id integer primary key default 1,
  alerta_stock_bajo boolean not null default true,
  alerta_stock_critico boolean not null default true,
  confirmacion_ventas boolean not null default true,
  alertas_mantenimiento boolean not null default true,
  alertas_vencimiento boolean not null default true,
  alertas_compras_pendientes boolean not null default true,
  notificaciones_correo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.config_umbrales (
  id integer primary key default 1,
  stock_bajo_porcentaje numeric(5,2) not null default 20,
  stock_critico_porcentaje numeric(5,2) not null default 10,
  dias_mantenimiento integer not null default 30,
  dias_vencimiento integer not null default 7,
  parametros_extra jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sucursal (
  id bigint generated by default as identity primary key,
  nombre text not null,
  direccion text not null,
  telefono text not null,
  encargado text,
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.configuracion_auditoria (
  id bigint generated by default as identity primary key,
  modulo text not null,
  entidad text not null,
  entidad_id text,
  accion text not null,
  usuario text,
  antes jsonb,
  despues jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_sucursal_activa on public.sucursal(activa);
create index if not exists idx_sucursal_created_at on public.sucursal(created_at desc);
create index if not exists idx_configuracion_auditoria_created_at on public.configuracion_auditoria(created_at desc);

insert into public.config_empresa (id, nombre_empresa, nit, direccion, telefono, correo, logo_url)
values (1, 'AMATI HIELO', 'CF', 'Dirección pendiente', '0000-0000', 'contacto@amati.com', null)
on conflict (id) do nothing;

insert into public.config_impuestos (id, iva_activo, iva_porcentaje, otros_impuestos)
values (1, true, 12, '[]'::jsonb)
on conflict (id) do nothing;

insert into public.config_notificaciones (id)
values (1)
on conflict (id) do nothing;

insert into public.config_umbrales (id)
values (1)
on conflict (id) do nothing;

create or replace function public.sucursal_tiene_relaciones(p_sucursal_id bigint)
returns boolean
language plpgsql
as $$
declare
  v_tabla text;
  v_tiene_relacion boolean;
begin
  foreach v_tabla in array array[
    'venta_pos',
    'venta_pos_detalle',
    'movimiento_inventario',
    'producto',
    'receta',
    'plan_produccion',
    'produccion'
  ] loop
    if exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = v_tabla
        and column_name = 'sucursal_id'
    ) then
      execute format('select exists(select 1 from public.%I where sucursal_id = $1)', v_tabla)
      into v_tiene_relacion
      using p_sucursal_id;

      if v_tiene_relacion then
        return true;
      end if;
    end if;
  end loop;

  return false;
end;
$$;

create or replace function public.registrar_venta_pos_consumo_directo(
  p_cliente text default null,
  p_items jsonb default null,
  p_metodo_pago text default 'Efectivo',
  p_necesita_factura boolean default false,
  p_nit text default null,
  p_nombre_cliente text default null,
  p_numero_telefono text default null,
  p_usuario text default null
)
returns public.venta_pos
language plpgsql
as $$
declare
  v_venta public.venta_pos%rowtype;
  v_ticket text;
  v_subtotal numeric(12,2);
  v_iva numeric(12,2);
  v_total numeric(12,2);
  v_item record;
  v_req record;
  v_producto public.producto%rowtype;
  v_iva_activo boolean;
  v_iva_porcentaje numeric(5,2);
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La venta debe incluir al menos un producto.';
  end if;

  select
    coalesce(iva_activo, true),
    coalesce(iva_porcentaje, 12)
  into v_iva_activo, v_iva_porcentaje
  from public.config_impuestos
  where id = 1;

  v_iva_activo := coalesce(v_iva_activo, true);
  v_iva_porcentaje := coalesce(v_iva_porcentaje, 12);

  for v_item in
    select *
    from jsonb_to_recordset(p_items) as item(
      receta_id bigint,
      cantidad numeric,
      precio_unitario numeric
    )
  loop
    if v_item.receta_id is null then
      raise exception 'Todos los productos de venta deben tener receta.';
    end if;

    if v_item.cantidad is null or v_item.cantidad <= 0 then
      raise exception 'La cantidad vendida debe ser mayor a 0.';
    end if;

    if not exists (select 1 from public.receta where id = v_item.receta_id) then
      raise exception 'No se encontró una receta de la venta.';
    end if;

    if not exists (select 1 from public.ingrediente_receta where receta_id = v_item.receta_id) then
      raise exception 'La receta no tiene BOM definido.';
    end if;

    if exists (
      select 1
      from public.ingrediente_receta
      where receta_id = v_item.receta_id
        and producto_id is null
    ) then
      raise exception 'Todos los ingredientes del BOM deben estar vinculados a un producto de inventario.';
    end if;
  end loop;

  for v_req in
    with items as (
      select *
      from jsonb_to_recordset(p_items) as item(
        receta_id bigint,
        cantidad numeric,
        precio_unitario numeric
      )
    )
    select
      ing.producto_id,
      sum(ing.cantidad * items.cantidad)::numeric(12,2) as cantidad_requerida
    from items
    join public.ingrediente_receta ing on ing.receta_id = items.receta_id
    group by ing.producto_id
  loop
    select *
    into v_producto
    from public.producto
    where id = v_req.producto_id
    for update;

    if not found then
      raise exception 'No se encontró un insumo de inventario vinculado al BOM.';
    end if;

    if v_producto.stock < v_req.cantidad_requerida then
      raise exception 'Inventario insuficiente para %. Disponible: %, requerido: %.',
        v_producto.nombre,
        v_producto.stock,
        v_req.cantidad_requerida;
    end if;
  end loop;

  select
    coalesce(sum(coalesce(precio_unitario, 0) * cantidad), 0)::numeric(12,2)
  into v_subtotal
  from jsonb_to_recordset(p_items) as item(
    receta_id bigint,
    cantidad numeric,
    precio_unitario numeric
  );

  if v_iva_activo then
    v_iva := round(v_subtotal * (v_iva_porcentaje / 100), 2);
  else
    v_iva := 0;
  end if;

  v_total := v_subtotal + v_iva;
  v_ticket := 'TKT-' || to_char(now(), 'YYYYMMDDHH24MISS') || '-' || floor(random() * 1000)::int;

  insert into public.venta_pos (
    ticket,
    cliente,
    metodo_pago,
    subtotal,
    iva,
    total,
    usuario,
    necesita_factura,
    nit,
    nombre_cliente,
    numero_telefono
  )
  values (
    v_ticket,
    nullif(btrim(coalesce(p_cliente, '')), ''),
    coalesce(nullif(btrim(p_metodo_pago), ''), 'Efectivo'),
    v_subtotal,
    v_iva,
    v_total,
    nullif(btrim(coalesce(p_usuario, '')), ''),
    coalesce(p_necesita_factura, false),
    nullif(btrim(coalesce(p_nit, '')), ''),
    nullif(btrim(coalesce(p_nombre_cliente, '')), ''),
    nullif(btrim(coalesce(p_numero_telefono, '')), '')
  )
  returning * into v_venta;

  insert into public.venta_pos_detalle (
    venta_id,
    receta_id,
    cantidad,
    precio_unitario,
    total
  )
  select
    v_venta.id,
    item.receta_id,
    item.cantidad,
    coalesce(item.precio_unitario, 0),
    coalesce(item.precio_unitario, 0) * item.cantidad
  from jsonb_to_recordset(p_items) as item(
    receta_id bigint,
    cantidad numeric,
    precio_unitario numeric
  );

  for v_req in
    with items as (
      select *
      from jsonb_to_recordset(p_items) as item(
        receta_id bigint,
        cantidad numeric,
        precio_unitario numeric
      )
    )
    select
      ing.producto_id,
      sum(ing.cantidad * items.cantidad)::numeric(12,2) as cantidad_requerida
    from items
    join public.ingrediente_receta ing on ing.receta_id = items.receta_id
    group by ing.producto_id
  loop
    update public.producto
    set stock = stock - v_req.cantidad_requerida,
        updated_at = now()
    where id = v_req.producto_id;

    insert into public.movimiento_inventario (
      producto_id,
      tipo,
      cantidad,
      cantidad_compra,
      motivo,
      usuario
    )
    values (
      v_req.producto_id,
      'Salida',
      v_req.cantidad_requerida,
      v_req.cantidad_requerida,
      'Venta POS ' || v_venta.ticket,
      nullif(btrim(coalesce(p_usuario, '')), '')
    );
  end loop;

  return v_venta;
end;
$$;