-- Catalogo de roles y relacion normalizada desde profiles.

create table if not exists public.rol (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.rol (nombre, descripcion, activo, es_sistema, orden)
values
  ('Superusuario', 'Acceso total al sistema y configuracion critica.', true, true, 1),
  ('Administrador', 'Administracion operativa de usuarios, catalogos y procesos.', true, true, 2),
  ('Operario', 'Acceso operativo a las funciones del dia a dia.', true, true, 3)
on conflict (nombre) do update
  set descripcion = excluded.descripcion,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

alter table public.profiles
  add column if not exists rol_id bigint references public.rol(id);

update public.profiles p
set rol_id = r.id
from public.rol r
where p.rol_id is null
  and r.nombre = coalesce(nullif(p.rol, ''), 'Operario');

update public.profiles p
set rol_id = r.id
from public.rol r
where p.rol_id is null
  and r.nombre = 'Operario';

alter table public.profiles
  alter column rol_id set not null;

do $$
declare
  v_operario_id bigint;
begin
  select id into v_operario_id
  from public.rol
  where nombre = 'Operario';

  execute format('alter table public.profiles alter column rol_id set default %s', v_operario_id);
end;
$$;

drop index if exists idx_profiles_rol;
create index if not exists idx_profiles_rol_id on public.profiles (rol_id);

alter table public.profiles
  drop column if exists rol;

create or replace function public.is_admin_profile()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  user_role text;
  user_state text;
begin
  select r.nombre, p.estado
    into user_role, user_state
  from public.profiles p
  join public.rol r on r.id = p.rol_id
  where p.id = auth.uid();

  return user_state = 'Activo' and user_role in ('Superusuario', 'Administrador');
end;
$$;

do $$
declare
  v_tabla_id bigint;
begin
  insert into public.tabla_estructura (
    nombre_visible,
    nombre_interno,
    descripcion,
    modulo,
    es_sistema
  )
  values (
    'Roles',
    'rol',
    'Catalogo de roles y permisos base del sistema',
    'Seguridad y Acceso',
    true
  )
  on conflict (nombre_interno) do update
    set nombre_visible = excluded.nombre_visible,
        descripcion = excluded.descripcion,
        modulo = excluded.modulo,
        es_sistema = true,
        updated_at = now()
  returning id into v_tabla_id;

  delete from public.campo_estructura
  where tabla_id = v_tabla_id;

  insert into public.campo_estructura (
    tabla_id,
    nombre,
    tipo_dato,
    descripcion,
    requerido,
    unico,
    orden
  )
  select
    v_tabla_id,
    c.column_name,
    c.data_type,
    null,
    c.is_nullable = 'NO',
    c.column_name in ('id', 'nombre'),
    c.ordinal_position
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'rol'
  order by c.ordinal_position;
end;
$$;

do $$
declare
  v_profiles_id bigint;
begin
  select id into v_profiles_id
  from public.tabla_estructura
  where nombre_interno = 'profiles';

  if v_profiles_id is not null then
    delete from public.campo_estructura
    where tabla_id = v_profiles_id;

    insert into public.campo_estructura (
      tabla_id,
      nombre,
      tipo_dato,
      descripcion,
      requerido,
      unico,
      orden
    )
    select
      v_profiles_id,
      c.column_name,
      c.data_type,
      null,
      c.is_nullable = 'NO',
      c.column_name = 'id',
      c.ordinal_position
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.table_name = 'profiles'
    order by c.ordinal_position;
  end if;
end;
$$;
