-- Catalogo de estados de usuario y descripciones para diccionario de datos.

create table if not exists public.estado_usuario (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.estado_usuario (nombre, descripcion, activo, es_sistema, orden)
values
  ('Activo', 'Usuario habilitado para iniciar sesion y operar en el sistema.', true, true, 1),
  ('Inactivo', 'Usuario deshabilitado para operar en el sistema.', true, true, 2)
on conflict (nombre) do update
  set descripcion = excluded.descripcion,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

alter table public.profiles
  add column if not exists estado_usuario_id bigint references public.estado_usuario(id);

update public.profiles p
set estado_usuario_id = e.id
from public.estado_usuario e
where p.estado_usuario_id is null
  and e.nombre = coalesce(nullif(p.estado, ''), 'Activo');

update public.profiles p
set estado_usuario_id = e.id
from public.estado_usuario e
where p.estado_usuario_id is null
  and e.nombre = 'Activo';

alter table public.profiles
  alter column estado_usuario_id set not null;

do $$
declare
  v_activo_id bigint;
begin
  select id into v_activo_id
  from public.estado_usuario
  where nombre = 'Activo';

  execute format('alter table public.profiles alter column estado_usuario_id set default %s', v_activo_id);
end;
$$;

drop index if exists idx_profiles_estado;
create index if not exists idx_profiles_estado_usuario_id on public.profiles (estado_usuario_id);

alter table public.profiles
  drop column if exists estado;

create or replace function public.is_admin_profile()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  user_role text;
  user_state text;
begin
  select r.nombre, e.nombre
    into user_role, user_state
  from public.profiles p
  join public.rol r on r.id = p.rol_id
  join public.estado_usuario e on e.id = p.estado_usuario_id
  where p.id = auth.uid();

  return user_state = 'Activo' and user_role in ('Superusuario', 'Administrador');
end;
$$;

do $$
declare
  v_tabla_id bigint;
begin
  insert into public.tabla_estructura (
    nombre_visible,
    nombre_interno,
    descripcion,
    modulo,
    es_sistema
  )
  values (
    'Estados de Usuario',
    'estado_usuario',
    'Catalogo de estados disponibles para perfiles de usuario',
    'Seguridad y Acceso',
    true
  )
  on conflict (nombre_interno) do update
    set nombre_visible = excluded.nombre_visible,
        descripcion = excluded.descripcion,
        modulo = excluded.modulo,
        es_sistema = true,
        updated_at = now()
  returning id into v_tabla_id;

  delete from public.campo_estructura
  where tabla_id = v_tabla_id;

  insert into public.campo_estructura (
    tabla_id,
    nombre,
    tipo_dato,
    descripcion,
    requerido,
    unico,
    orden
  )
  select
    v_tabla_id,
    c.column_name,
    c.data_type,
    case c.column_name
      when 'id' then 'Identificador unico del estado de usuario.'
      when 'nombre' then 'Nombre del estado de usuario.'
      when 'descripcion' then 'Descripcion funcional del estado de usuario.'
      when 'activo' then 'Indica si el estado esta disponible para seleccion.'
      when 'es_sistema' then 'Indica si el registro pertenece a la configuracion base del sistema.'
      when 'orden' then 'Orden de visualizacion del estado.'
      when 'created_at' then 'Fecha y hora de creacion del registro.'
      when 'updated_at' then 'Fecha y hora de ultima actualizacion del registro.'
      else null
    end,
    c.is_nullable = 'NO',
    c.column_name in ('id', 'nombre'),
    c.ordinal_position
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'estado_usuario'
  order by c.ordinal_position;
end;
$$;

update public.campo_estructura c
set descripcion = case c.nombre
  when 'id' then 'Identificador unico del rol.'
  when 'nombre' then 'Nombre del rol.'
  when 'descripcion' then 'Descripcion funcional del rol.'
  when 'activo' then 'Indica si el rol esta disponible para seleccion.'
  when 'es_sistema' then 'Indica si el registro pertenece a la configuracion base del sistema.'
  when 'orden' then 'Orden de visualizacion del rol.'
  when 'created_at' then 'Fecha y hora de creacion del registro.'
  when 'updated_at' then 'Fecha y hora de ultima actualizacion del registro.'
  else c.descripcion
end
from public.tabla_estructura t
where t.id = c.tabla_id
  and t.nombre_interno = 'rol';

do $$
declare
  v_profiles_id bigint;
begin
  select id into v_profiles_id
  from public.tabla_estructura
  where nombre_interno = 'profiles';

  if v_profiles_id is not null then
    delete from public.campo_estructura
    where tabla_id = v_profiles_id;

    insert into public.campo_estructura (
      tabla_id,
      nombre,
      tipo_dato,
      descripcion,
      requerido,
      unico,
      orden
    )
    select
      v_profiles_id,
      c.column_name,
      c.data_type,
      case c.column_name
        when 'id' then 'Identificador del usuario relacionado con auth.users.'
        when 'nombre' then 'Nombre completo del usuario.'
        when 'usuario' then 'Nombre de usuario unico para iniciar sesion o identificar al perfil.'
        when 'email' then 'Correo electronico unico del usuario.'
        when 'rol_id' then 'Referencia al rol asignado al usuario.'
        when 'estado_usuario_id' then 'Referencia al estado actual del usuario.'
        when 'ultimo_acceso' then 'Fecha y hora del ultimo acceso registrado.'
        when 'created_at' then 'Fecha y hora de creacion del perfil.'
        when 'updated_at' then 'Fecha y hora de ultima actualizacion del perfil.'
        else null
      end,
      c.is_nullable = 'NO',
      c.column_name in ('id', 'usuario', 'email'),
      c.ordinal_position
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.table_name = 'profiles'
    order by c.ordinal_position;
  end if;
end;
$$;
