-- Catalogo de categorias de inventario para reemplazar valores quemados en UI y backend.

create table if not exists public.catalogo_categoria_inventario (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.catalogo_categoria_inventario (
  codigo,
  nombre,
  descripcion,
  activo,
  es_sistema,
  orden
)
values
  ('MP', 'Materia Prima', 'Insumos principales utilizados en produccion.', true, true, 1),
  ('SUM', 'Suministros', 'Materiales de apoyo y consumo operativo.', true, true, 2)
on conflict (codigo) do update
  set nombre = excluded.nombre,
      descripcion = excluded.descripcion,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

do $$
declare
  v_tabla_id bigint;
begin
  insert into public.tabla_estructura (
    nombre_visible,
    nombre_interno,
    descripcion,
    modulo,
    es_sistema
  )
  values (
    'Categorias de Inventario',
    'catalogo_categoria_inventario',
    'Catalogo base de categorias usadas en el modulo de inventario',
    'Inventarios',
    true
  )
  on conflict (nombre_interno) do update
    set nombre_visible = excluded.nombre_visible,
        descripcion = excluded.descripcion,
        modulo = excluded.modulo,
        es_sistema = true,
        updated_at = now()
  returning id into v_tabla_id;

  delete from public.campo_estructura
  where tabla_id = v_tabla_id;

  insert into public.campo_estructura (
    tabla_id,
    nombre,
    tipo_dato,
    descripcion,
    requerido,
    unico,
    orden
  )
  select
    v_tabla_id,
    c.column_name,
    c.data_type,
    case c.column_name
      when 'id' then 'Identificador unico de la categoria.'
      when 'codigo' then 'Codigo corto de la categoria, usado como prefijo de articulos.'
      when 'nombre' then 'Nombre visible de la categoria.'
      when 'descripcion' then 'Descripcion funcional de la categoria.'
      when 'activo' then 'Indica si la categoria esta disponible para uso.'
      when 'es_sistema' then 'Indica si el registro pertenece a la configuracion base.'
      when 'orden' then 'Orden de visualizacion de la categoria.'
      when 'created_at' then 'Fecha y hora de creacion del registro.'
      when 'updated_at' then 'Fecha y hora de ultima actualizacion del registro.'
      else null
    end,
    c.is_nullable = 'NO',
    c.column_name in ('id', 'codigo', 'nombre'),
    c.ordinal_position
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'catalogo_categoria_inventario'
  order by c.ordinal_position;
end;
$$;