-- Catalogo de departamentos y municipios de Guatemala.
-- Agrega la ubicacion (departamento y municipio) al perfil de usuario.
-- El pais es fijo (Guatemala) y no se almacena como columna.

create table if not exists public.departamento (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.municipio (
  id bigint generated by default as identity primary key,
  departamento_id bigint not null references public.departamento(id),
  nombre text not null,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (departamento_id, nombre)
);

insert into public.departamento (codigo, nombre, activo, es_sistema, orden)
values
  ('01', 'Guatemala', true, true, 1),
  ('02', 'El Progreso', true, true, 2),
  ('03', 'Sacatepéquez', true, true, 3),
  ('04', 'Chimaltenango', true, true, 4),
  ('05', 'Escuintla', true, true, 5),
  ('06', 'Santa Rosa', true, true, 6),
  ('07', 'Sololá', true, true, 7),
  ('08', 'Totonicapán', true, true, 8),
  ('09', 'Quetzaltenango', true, true, 9),
  ('10', 'Suchitepéquez', true, true, 10),
  ('11', 'Retalhuleu', true, true, 11),
  ('12', 'San Marcos', true, true, 12),
  ('13', 'Huehuetenango', true, true, 13),
  ('14', 'Quiché', true, true, 14),
  ('15', 'Baja Verapaz', true, true, 15),
  ('16', 'Alta Verapaz', true, true, 16),
  ('17', 'Petén', true, true, 17),
  ('18', 'Izabal', true, true, 18),
  ('19', 'Zacapa', true, true, 19),
  ('20', 'Chiquimula', true, true, 20),
  ('21', 'Jalapa', true, true, 21),
  ('22', 'Jutiapa', true, true, 22)
on conflict (codigo) do update
  set nombre = excluded.nombre,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

-- Seed de los 340 municipios oficiales de Guatemala (lista INE).
insert into public.municipio (departamento_id, nombre, activo, es_sistema, orden)
select d.id, m.nombre, true, true, m.orden
from (
  values
    ('01', 1, 'Guatemala'),
    ('01', 2, 'Amatitlán'),
    ('01', 3, 'Chinautla'),
    ('01', 4, 'Chuarrancho'),
    ('01', 5, 'Fraijanes'),
    ('01', 6, 'Mixco'),
    ('01', 7, 'Palencia'),
    ('01', 8, 'San José del Golfo'),
    ('01', 9, 'San José Pinula'),
    ('01', 10, 'San Juan Sacatepéquez'),
    ('01', 11, 'San Miguel Petapa'),
    ('01', 12, 'San Pedro Ayampuc'),
    ('01', 13, 'San Pedro Sacatepéquez'),
    ('01', 14, 'San Raymundo'),
    ('01', 15, 'Santa Catarina Pinula'),
    ('01', 16, 'Villa Canales'),
    ('01', 17, 'Villa Nueva'),
    ('02', 1, 'El Jícaro'),
    ('02', 2, 'Guastatoya'),
    ('02', 3, 'Morazán'),
    ('02', 4, 'San Agustín Acasaguastlán'),
    ('02', 5, 'San Antonio La Paz'),
    ('02', 6, 'San Cristóbal Acasaguastlán'),
    ('02', 7, 'Sanarate'),
    ('02', 8, 'Sansare'),
    ('03', 1, 'Alotenango'),
    ('03', 2, 'Antigua Guatemala'),
    ('03', 3, 'Ciudad Vieja'),
    ('03', 4, 'Jocotenango'),
    ('03', 5, 'Magdalena Milpas Altas'),
    ('03', 6, 'Pastores'),
    ('03', 7, 'San Antonio Aguas Calientes'),
    ('03', 8, 'San Bartolomé Milpas Altas'),
    ('03', 9, 'San Lucas Sacatepéquez'),
    ('03', 10, 'San Miguel Dueñas'),
    ('03', 11, 'Santa Catarina Barahona'),
    ('03', 12, 'Santa Lucía Milpas Altas'),
    ('03', 13, 'Santa María de Jesús'),
    ('03', 14, 'Santiago Sacatepéquez'),
    ('03', 15, 'Santo Domingo Xenacoj'),
    ('03', 16, 'Sumpango'),
    ('04', 1, 'Acatenango'),
    ('04', 2, 'Chimaltenango'),
    ('04', 3, 'El Tejar'),
    ('04', 4, 'Parramos'),
    ('04', 5, 'Patzicía'),
    ('04', 6, 'Patzún'),
    ('04', 7, 'Pochuta'),
    ('04', 8, 'San Andrés Itzapa'),
    ('04', 9, 'San José Poaquil'),
    ('04', 10, 'San Juan Comalapa'),
    ('04', 11, 'San Martín Jilotepeque'),
    ('04', 12, 'Santa Apolonia'),
    ('04', 13, 'Santa Cruz Balanyá'),
    ('04', 14, 'Tecpán'),
    ('04', 15, 'Yepocapa'),
    ('04', 16, 'Zaragoza'),
    ('05', 1, 'Escuintla'),
    ('05', 2, 'Guanagazapa'),
    ('05', 3, 'Iztapa'),
    ('05', 4, 'La Democracia'),
    ('05', 5, 'La Gomera'),
    ('05', 6, 'Masagua'),
    ('05', 7, 'Nueva Concepción'),
    ('05', 8, 'Palín'),
    ('05', 9, 'San José'),
    ('05', 10, 'San Vicente Pacaya'),
    ('05', 11, 'Santa Lucía Cotzumalguapa'),
    ('05', 12, 'Sipacate'),
    ('05', 13, 'Siquinalá'),
    ('05', 14, 'Tiquisate'),
    ('06', 1, 'Barberena'),
    ('06', 2, 'Casillas'),
    ('06', 3, 'Chiquimulilla'),
    ('06', 4, 'Cuilapa'),
    ('06', 5, 'Guazacapán'),
    ('06', 6, 'Nueva Santa Rosa'),
    ('06', 7, 'Oratorio'),
    ('06', 8, 'Pueblo Nuevo Viñas'),
    ('06', 9, 'San Juan Tecuaco'),
    ('06', 10, 'San Rafael las Flores'),
    ('06', 11, 'Santa Cruz Naranjo'),
    ('06', 12, 'Santa María Ixhuatán'),
    ('06', 13, 'Santa Rosa de Lima'),
    ('06', 14, 'Taxisco'),
    ('07', 1, 'Concepción'),
    ('07', 2, 'Nahualá'),
    ('07', 3, 'Panajachel'),
    ('07', 4, 'San Andrés Semetabaj'),
    ('07', 5, 'San Antonio Palopó'),
    ('07', 6, 'San José Chacayá'),
    ('07', 7, 'San Juan La Laguna'),
    ('07', 8, 'San Lucas Tolimán'),
    ('07', 9, 'San Marcos La Laguna'),
    ('07', 10, 'San Pablo La Laguna'),
    ('07', 11, 'San Pedro La Laguna'),
    ('07', 12, 'Santa Catarina Ixtahuacán'),
    ('07', 13, 'Santa Catarina Palopó'),
    ('07', 14, 'Santa Clara La Laguna'),
    ('07', 15, 'Santa Cruz La Laguna'),
    ('07', 16, 'Santa Lucía Utatlán'),
    ('07', 17, 'Santa María Visitación'),
    ('07', 18, 'Santiago Atitlán'),
    ('07', 19, 'Sololá'),
    ('08', 1, 'Momostenango'),
    ('08', 2, 'San Andrés Xecul'),
    ('08', 3, 'San Bartolo'),
    ('08', 4, 'San Cristóbal Totonicapán'),
    ('08', 5, 'San Francisco El Alto'),
    ('08', 6, 'Santa Lucía La Reforma'),
    ('08', 7, 'Santa María Chiquimula'),
    ('08', 8, 'Totonicapán'),
    ('09', 1, 'Almolonga'),
    ('09', 2, 'Cabricán'),
    ('09', 3, 'Cajolá'),
    ('09', 4, 'Cantel'),
    ('09', 5, 'Coatepeque'),
    ('09', 6, 'Colomba Costa Cuca'),
    ('09', 7, 'Concepción Chiquirichapa'),
    ('09', 8, 'El Palmar'),
    ('09', 9, 'Flores Costa Cuca'),
    ('09', 10, 'Génova'),
    ('09', 11, 'Huitán'),
    ('09', 12, 'La Esperanza'),
    ('09', 13, 'Olintepeque'),
    ('09', 14, 'Palestina de Los Altos'),
    ('09', 15, 'Quetzaltenango'),
    ('09', 16, 'Salcajá'),
    ('09', 17, 'San Carlos Sija'),
    ('09', 18, 'San Francisco La Unión'),
    ('09', 19, 'San Juan Ostuncalco'),
    ('09', 20, 'San Martín Sacatepéquez'),
    ('09', 21, 'San Mateo'),
    ('09', 22, 'San Miguel Sigüilá'),
    ('09', 23, 'Sibilia'),
    ('09', 24, 'Zunil'),
    ('10', 1, 'Chicacao'),
    ('10', 2, 'Cuyotenango'),
    ('10', 3, 'Mazatenango'),
    ('10', 4, 'Patulul'),
    ('10', 5, 'Pueblo Nuevo'),
    ('10', 6, 'Río Bravo'),
    ('10', 7, 'Samayac'),
    ('10', 8, 'San Antonio Suchitepéquez'),
    ('10', 9, 'San Bernardino'),
    ('10', 10, 'San Francisco Zapotitlán'),
    ('10', 11, 'San Gabriel'),
    ('10', 12, 'San José El Ídolo'),
    ('10', 13, 'San José La Máquina'),
    ('10', 14, 'San Juan Bautista'),
    ('10', 15, 'San Lorenzo'),
    ('10', 16, 'San Miguel Panán'),
    ('10', 17, 'San Pablo Jocopilas'),
    ('10', 18, 'Santa Bárbara'),
    ('10', 19, 'Santo Domingo Suchitepéquez'),
    ('10', 20, 'Santo Tomás La Unión'),
    ('10', 21, 'Zunilito'),
    ('11', 1, 'Champerico'),
    ('11', 2, 'El Asintal'),
    ('11', 3, 'Nuevo San Carlos'),
    ('11', 4, 'Retalhuleu'),
    ('11', 5, 'San Andrés Villa Seca'),
    ('11', 6, 'San Felipe'),
    ('11', 7, 'San Martín Zapotitlán'),
    ('11', 8, 'San Sebastián'),
    ('11', 9, 'Santa Cruz Muluá'),
    ('12', 1, 'Ayutla'),
    ('12', 2, 'Catarina'),
    ('12', 3, 'Comitancillo'),
    ('12', 4, 'Concepción Tutuapa'),
    ('12', 5, 'El Quetzal'),
    ('12', 6, 'El Tumbador'),
    ('12', 7, 'Esquipulas Palo Gordo'),
    ('12', 8, 'Ixchiguán'),
    ('12', 9, 'La Blanca'),
    ('12', 10, 'La Reforma'),
    ('12', 11, 'Malacatán'),
    ('12', 12, 'Nuevo Progreso'),
    ('12', 13, 'Ocós'),
    ('12', 14, 'Pajapita'),
    ('12', 15, 'Río Blanco'),
    ('12', 16, 'San Antonio Sacatepéquez'),
    ('12', 17, 'San Cristóbal Cucho'),
    ('12', 18, 'San José El Rodeo'),
    ('12', 19, 'San José Ojetenam'),
    ('12', 20, 'San Lorenzo'),
    ('12', 21, 'San Marcos'),
    ('12', 22, 'San Miguel Ixtahuacán'),
    ('12', 23, 'San Pablo'),
    ('12', 24, 'San Pedro Sacatepéquez'),
    ('12', 25, 'San Rafael Pie de la Cuesta'),
    ('12', 26, 'Sibinal'),
    ('12', 27, 'Sipacapa'),
    ('12', 28, 'Tacaná'),
    ('12', 29, 'Tajumulco'),
    ('12', 30, 'Tejutla'),
    ('13', 1, 'Aguacatán'),
    ('13', 2, 'Chiantla'),
    ('13', 3, 'Colotenango'),
    ('13', 4, 'Concepción Huista'),
    ('13', 5, 'Cuilco'),
    ('13', 6, 'Huehuetenango'),
    ('13', 7, 'Jacaltenango'),
    ('13', 8, 'La Democracia'),
    ('13', 9, 'La Libertad'),
    ('13', 10, 'Malacatancito'),
    ('13', 11, 'Nentón'),
    ('13', 12, 'Petatán'),
    ('13', 13, 'San Antonio Huista'),
    ('13', 14, 'San Gaspar Ixchil'),
    ('13', 15, 'San Ildefonso Ixtahuacán'),
    ('13', 16, 'San Juan Atitán'),
    ('13', 17, 'San Juan Ixcoy'),
    ('13', 18, 'San Mateo Ixtatán'),
    ('13', 19, 'San Miguel Acatán'),
    ('13', 20, 'San Pedro Nectá'),
    ('13', 21, 'San Pedro Soloma'),
    ('13', 22, 'San Rafael La Independencia'),
    ('13', 23, 'San Rafael Pétzal'),
    ('13', 24, 'San Sebastián Coatán'),
    ('13', 25, 'San Sebastián Huehuetenango'),
    ('13', 26, 'Santa Ana Huista'),
    ('13', 27, 'Santa Bárbara'),
    ('13', 28, 'Santa Cruz Barillas'),
    ('13', 29, 'Santa Eulalia'),
    ('13', 30, 'Santiago Chimaltenango'),
    ('13', 31, 'Tectitán'),
    ('13', 32, 'Todos Santos Cuchumatán'),
    ('13', 33, 'Unión Cantinil'),
    ('14', 1, 'Canillá'),
    ('14', 2, 'Chajul'),
    ('14', 3, 'Chicamán'),
    ('14', 4, 'Chiché'),
    ('14', 5, 'Chinique'),
    ('14', 6, 'Cunén'),
    ('14', 7, 'Ixcán'),
    ('14', 8, 'Joyabaj'),
    ('14', 9, 'Nebaj'),
    ('14', 10, 'Pachalum'),
    ('14', 11, 'Patzité'),
    ('14', 12, 'Sacapulas'),
    ('14', 13, 'San Andrés Sajcabajá'),
    ('14', 14, 'San Antonio Ilotenango'),
    ('14', 15, 'San Bartolomé Jocotenango'),
    ('14', 16, 'San Juan Cotzal'),
    ('14', 17, 'San Pedro Jocopilas'),
    ('14', 18, 'Santa Cruz del Quiché'),
    ('14', 19, 'Santo Tomás Chichicastenango'),
    ('14', 20, 'Uspantán'),
    ('14', 21, 'Zacualpa'),
    ('15', 1, 'Cubulco'),
    ('15', 2, 'Granados'),
    ('15', 3, 'Purulhá'),
    ('15', 4, 'Rabinal'),
    ('15', 5, 'Salamá'),
    ('15', 6, 'San Jerónimo'),
    ('15', 7, 'San Miguel Chicaj'),
    ('15', 8, 'Santa Cruz el Chol'),
    ('16', 1, 'Chahal'),
    ('16', 2, 'Chisec'),
    ('16', 3, 'Cobán'),
    ('16', 4, 'Fray Bartolomé de las Casas'),
    ('16', 5, 'Lanquín'),
    ('16', 6, 'Panzós'),
    ('16', 7, 'Raxruhá'),
    ('16', 8, 'San Cristóbal Verapaz'),
    ('16', 9, 'San Juan Chamelco'),
    ('16', 10, 'San Pedro Carchá'),
    ('16', 11, 'Santa Catalina La Tinta'),
    ('16', 12, 'Santa Cruz Verapaz'),
    ('16', 13, 'Senahú'),
    ('16', 14, 'Tactic'),
    ('16', 15, 'Tamahú'),
    ('16', 16, 'Tucurú'),
    ('16', 17, 'Cahabón'),
    ('17', 1, 'Dolores'),
    ('17', 2, 'El Chal'),
    ('17', 3, 'Flores'),
    ('17', 4, 'La Libertad'),
    ('17', 5, 'Las Cruces'),
    ('17', 6, 'Melchor de Mencos'),
    ('17', 7, 'Poptún'),
    ('17', 8, 'San Andrés'),
    ('17', 9, 'San Benito'),
    ('17', 10, 'San Francisco'),
    ('17', 11, 'San José'),
    ('17', 12, 'San Luis'),
    ('17', 13, 'Santa Ana'),
    ('17', 14, 'Sayaxché'),
    ('18', 1, 'El Estor'),
    ('18', 2, 'Livingston'),
    ('18', 3, 'Los Amates'),
    ('18', 4, 'Morales'),
    ('18', 5, 'Puerto Barrios'),
    ('19', 1, 'Cabañas'),
    ('19', 2, 'Estanzuela'),
    ('19', 3, 'Gualán'),
    ('19', 4, 'Huité'),
    ('19', 5, 'La Unión'),
    ('19', 6, 'Río Hondo'),
    ('19', 7, 'San Diego'),
    ('19', 8, 'San Jorge'),
    ('19', 9, 'Teculután'),
    ('19', 10, 'Usumatlán'),
    ('19', 11, 'Zacapa'),
    ('20', 1, 'Camotán'),
    ('20', 2, 'Chiquimula'),
    ('20', 3, 'Concepción Las Minas'),
    ('20', 4, 'Esquipulas'),
    ('20', 5, 'Ipala'),
    ('20', 6, 'Jocotán'),
    ('20', 7, 'Olopa'),
    ('20', 8, 'Quezaltepeque'),
    ('20', 9, 'San Jacinto'),
    ('20', 10, 'San José la Arada'),
    ('20', 11, 'San Juan La Ermita'),
    ('21', 1, 'Jalapa'),
    ('21', 2, 'Mataquescuintla'),
    ('21', 3, 'Monjas'),
    ('21', 4, 'San Carlos Alzatate'),
    ('21', 5, 'San Luis Jilotepeque'),
    ('21', 6, 'San Manuel Chaparrón'),
    ('21', 7, 'San Pedro Pinula'),
    ('22', 1, 'Agua Blanca'),
    ('22', 2, 'Asunción Mita'),
    ('22', 3, 'Atescatempa'),
    ('22', 4, 'Comapa'),
    ('22', 5, 'Conguaco'),
    ('22', 6, 'El Adelanto'),
    ('22', 7, 'El Progreso'),
    ('22', 8, 'Jalpatagua'),
    ('22', 9, 'Jerez'),
    ('22', 10, 'Jutiapa'),
    ('22', 11, 'Moyuta'),
    ('22', 12, 'Pasaco'),
    ('22', 13, 'Quesada'),
    ('22', 14, 'San José Acatempa'),
    ('22', 15, 'Santa Catarina Mita'),
    ('22', 16, 'Yupiltepeque'),
    ('22', 17, 'Zapotitlán')
) as m(departamento_codigo, orden, nombre)
join public.departamento d on d.codigo = m.departamento_codigo
on conflict (departamento_id, nombre) do update
  set activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

-- Ubicacion en profiles (departamento y municipio).
alter table public.profiles
  add column if not exists departamento_id bigint references public.departamento(id),
  add column if not exists municipio_id bigint references public.municipio(id);

-- Backfill de usuarios existentes: Departamento de Guatemala / Municipio de Guatemala.
update public.profiles p
set departamento_id = d.id
from public.departamento d
where p.departamento_id is null
  and d.nombre = 'Guatemala';

update public.profiles p
set municipio_id = m.id
from public.municipio m
join public.departamento d on d.id = m.departamento_id
where p.municipio_id is null
  and d.nombre = 'Guatemala'
  and m.nombre = 'Guatemala';

alter table public.profiles
  alter column departamento_id set not null,
  alter column municipio_id set not null;

create index if not exists idx_profiles_departamento_id on public.profiles (departamento_id);
create index if not exists idx_profiles_municipio_id on public.profiles (municipio_id);
create index if not exists idx_municipio_departamento_id on public.municipio (departamento_id);

-- Diccionario de datos: departamento.
do $$
declare
  v_tabla_id bigint;
begin
  insert into public.tabla_estructura (
    nombre_visible,
    nombre_interno,
    descripcion,
    modulo,
    es_sistema
  )
  values (
    'Departamentos',
    'departamento',
    'Catalogo de departamentos de Guatemala',
    'Seguridad y Acceso',
    true
  )
  on conflict (nombre_interno) do update
    set nombre_visible = excluded.nombre_visible,
        descripcion = excluded.descripcion,
        modulo = excluded.modulo,
        es_sistema = true,
        updated_at = now()
  returning id into v_tabla_id;

  delete from public.campo_estructura
  where tabla_id = v_tabla_id;

  insert into public.campo_estructura (
    tabla_id,
    nombre,
    tipo_dato,
    descripcion,
    requerido,
    unico,
    orden
  )
  select
    v_tabla_id,
    c.column_name,
    c.data_type,
    case c.column_name
      when 'id' then 'Identificador unico del departamento.'
      when 'codigo' then 'Codigo oficial de dos digitos del departamento.'
      when 'nombre' then 'Nombre del departamento de Guatemala.'
      when 'descripcion' then 'Descripcion funcional del departamento.'
      when 'activo' then 'Indica si el departamento esta disponible para seleccion.'
      when 'es_sistema' then 'Indica si el registro pertenece a la configuracion base del sistema.'
      when 'orden' then 'Orden de visualizacion del departamento.'
      when 'created_at' then 'Fecha y hora de creacion del registro.'
      when 'updated_at' then 'Fecha y hora de ultima actualizacion del registro.'
      else null
    end,
    c.is_nullable = 'NO',
    c.column_name in ('id', 'codigo', 'nombre'),
    c.ordinal_position
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'departamento'
  order by c.ordinal_position;
end;
$$;

-- Diccionario de datos: municipio.
do $$
declare
  v_tabla_id bigint;
begin
  insert into public.tabla_estructura (
    nombre_visible,
    nombre_interno,
    descripcion,
    modulo,
    es_sistema
  )
  values (
    'Municipios',
    'municipio',
    'Catalogo de municipios de Guatemala',
    'Seguridad y Acceso',
    true
  )
  on conflict (nombre_interno) do update
    set nombre_visible = excluded.nombre_visible,
        descripcion = excluded.descripcion,
        modulo = excluded.modulo,
        es_sistema = true,
        updated_at = now()
  returning id into v_tabla_id;

  delete from public.campo_estructura
  where tabla_id = v_tabla_id;

  insert into public.campo_estructura (
    tabla_id,
    nombre,
    tipo_dato,
    descripcion,
    requerido,
    unico,
    orden
  )
  select
    v_tabla_id,
    c.column_name,
    c.data_type,
    case c.column_name
      when 'id' then 'Identificador unico del municipio.'
      when 'departamento_id' then 'Referencia al departamento al que pertenece el municipio.'
      when 'nombre' then 'Nombre del municipio.'
      when 'descripcion' then 'Descripcion funcional del municipio.'
      when 'activo' then 'Indica si el municipio esta disponible para seleccion.'
      when 'es_sistema' then 'Indica si el registro pertenece a la configuracion base del sistema.'
      when 'orden' then 'Orden de visualizacion del municipio.'
      when 'created_at' then 'Fecha y hora de creacion del registro.'
      when 'updated_at' then 'Fecha y hora de ultima actualizacion del registro.'
      else null
    end,
    c.is_nullable = 'NO',
    c.column_name in ('id', 'departamento_id', 'nombre'),
    c.ordinal_position
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'municipio'
  order by c.ordinal_position;
end;
$$;

-- Refresca el diccionario de datos de profiles con la ubicacion del usuario.
do $$
declare
  v_profiles_id bigint;
begin
  select id into v_profiles_id
  from public.tabla_estructura
  where nombre_interno = 'profiles';

  if v_profiles_id is not null then
    delete from public.campo_estructura
    where tabla_id = v_profiles_id;

    insert into public.campo_estructura (
      tabla_id,
      nombre,
      tipo_dato,
      descripcion,
      requerido,
      unico,
      orden
    )
    select
      v_profiles_id,
      c.column_name,
      c.data_type,
      case c.column_name
        when 'id' then 'Identificador del usuario relacionado con auth.users.'
        when 'usuario' then 'Nombre de usuario unico para iniciar sesion o identificar al perfil.'
        when 'email' then 'Correo electronico unico del usuario.'
        when 'primer_nombre' then 'Primer nombre del usuario.'
        when 'segundo_nombre' then 'Segundo nombre del usuario (opcional).'
        when 'primer_apellido' then 'Primer apellido del usuario.'
        when 'segundo_apellido' then 'Segundo apellido del usuario (opcional).'
        when 'departamento_id' then 'Departamento de residencia o ubicacion del usuario.'
        when 'municipio_id' then 'Municipio de residencia o ubicacion del usuario.'
        when 'rol_id' then 'Referencia al rol asignado al usuario.'
        when 'estado_usuario_id' then 'Referencia al estado actual del usuario.'
        when 'ultimo_acceso' then 'Fecha y hora del ultimo acceso registrado.'
        when 'created_at' then 'Fecha y hora de creacion del perfil.'
        when 'updated_at' then 'Fecha y hora de ultima actualizacion del perfil.'
        else null
      end,
      c.is_nullable = 'NO',
      c.column_name in ('id', 'usuario', 'email'),
      c.ordinal_position
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.table_name = 'profiles'
    order by c.ordinal_position;
  end if;
end;
$$;
