-- Catalogos para reemplazar valores quemados en formularios y logica de la app:
-- metodo de pago (POS), categorias de receta, tipos de movimiento y estado de producto.
-- Cada catalogo se registra en tabla_estructura/campo_estructura para el diccionario de datos.
-- Idempotente: se puede ejecutar cuantas veces se necesite.

create or replace function public.registrar_estructura_catalogos(
  p_nombre_interno text,
  p_nombre_visible text,
  p_modulo text,
  p_descripcion text default null,
  p_es_sistema boolean default true,
  p_descripciones jsonb default '{}'::jsonb,
  p_unicos text[] default array['id']::text[]
)
returns void
language plpgsql
as $$
declare
  v_tabla_id bigint;
begin
  insert into public.tabla_estructura (
    nombre_visible,
    nombre_interno,
    descripcion,
    modulo,
    es_sistema
  )
  values (
    p_nombre_visible,
    p_nombre_interno,
    nullif(btrim(coalesce(p_descripcion, '')), ''),
    p_modulo,
    coalesce(p_es_sistema, true)
  )
  on conflict (nombre_interno) do update
    set nombre_visible = excluded.nombre_visible,
        descripcion = excluded.descripcion,
        modulo = excluded.modulo,
        es_sistema = excluded.es_sistema,
        updated_at = now()
  returning id into v_tabla_id;

  delete from public.campo_estructura
  where tabla_id = v_tabla_id;

  insert into public.campo_estructura (
    tabla_id,
    nombre,
    tipo_dato,
    descripcion,
    requerido,
    unico,
    orden
  )
  select
    v_tabla_id,
    c.column_name,
    c.data_type,
    nullif(btrim(coalesce(p_descripciones ->> c.column_name, '')), ''),
    c.is_nullable = 'NO',
    c.column_name = any(coalesce(p_unicos, array['id']::text[])),
    c.ordinal_position
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = p_nombre_interno
  order by c.ordinal_position;
end;
$$;

-- ============ 1. metodo_pago ============
create table if not exists public.metodo_pago (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.metodo_pago (nombre, descripcion, activo, es_sistema, orden)
values
  ('Efectivo', 'Pago en efectivo.', true, true, 1),
  ('Transferencia', 'Pago por transferencia o deposito bancario.', true, true, 2),
  ('Tarjeta', 'Pago con tarjeta de credito o debito.', true, true, 3)
on conflict (nombre) do update
  set descripcion = excluded.descripcion,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

select public.registrar_estructura_catalogos(
  'metodo_pago',
  'Metodos de Pago',
  'Punto de Venta',
  'Catalogo de formas de pago disponibles en el POS',
  true,
  '{"id":"Identificador unico del metodo de pago.","nombre":"Nombre del metodo de pago.","descripcion":"Descripcion funcional del metodo de pago.","activo":"Indica si el metodo de pago esta disponible para seleccion.","es_sistema":"Indica si el registro pertenece a la configuracion base del sistema.","orden":"Orden de visualizacion del metodo de pago.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','nombre']::text[]
);

-- ============ 2. catalogo_categoria_receta ============
create table if not exists public.catalogo_categoria_receta (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.catalogo_categoria_receta (codigo, nombre, descripcion, activo, es_sistema, orden)
values
  ('BEB', 'Bebidas', 'Recetas de bebidas preparadas para la venta.', true, true, 1),
  ('PT', 'Producto Terminado', 'Productos terminados listos para la venta.', true, true, 2)
on conflict (codigo) do update
  set nombre = excluded.nombre,
      descripcion = excluded.descripcion,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

select public.registrar_estructura_catalogos(
  'catalogo_categoria_receta',
  'Categorias de Recetas',
  'Produccion y Recetas',
  'Catalogo de categorias usadas en el modulo de recetas',
  true,
  '{"id":"Identificador unico de la categoria de receta.","codigo":"Codigo corto de la categoria, usado como prefijo de recetas.","nombre":"Nombre visible de la categoria de receta.","descripcion":"Descripcion funcional de la categoria de receta.","activo":"Indica si la categoria esta disponible para uso.","es_sistema":"Indica si el registro pertenece a la configuracion base.","orden":"Orden de visualizacion de la categoria.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','codigo','nombre']::text[]
);

-- ============ 3. tipo_movimiento ============
create table if not exists public.tipo_movimiento (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.tipo_movimiento (codigo, nombre, descripcion, activo, es_sistema, orden)
values
  ('E', 'Entrada', 'Aumenta el stock de un producto.', true, true, 1),
  ('S', 'Salida', 'Disminuye el stock de un producto.', true, true, 2),
  ('M', 'Merma', 'Pérdida o desperdicio registrado.', true, true, 3),
  ('A', 'Ajuste', 'Correccion de stock por conteo o auditoria.', true, true, 4)
on conflict (codigo) do update
  set nombre = excluded.nombre,
      descripcion = excluded.descripcion,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

select public.registrar_estructura_catalogos(
  'tipo_movimiento',
  'Tipos de Movimiento',
  'Inventarios',
  'Catalogo de tipos de movimiento de inventario',
  true,
  '{"id":"Identificador unico del tipo de movimiento.","codigo":"Codigo corto del tipo de movimiento.","nombre":"Nombre del tipo de movimiento.","descripcion":"Descripcion funcional del tipo de movimiento.","activo":"Indica si el tipo de movimiento esta disponible para uso.","es_sistema":"Indica si el registro pertenece a la configuracion base.","orden":"Orden de visualizacion del tipo de movimiento.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','codigo','nombre']::text[]
);

-- ============ 4. estado_producto ============
create table if not exists public.estado_producto (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.estado_producto (nombre, descripcion, activo, es_sistema, orden)
values
  ('Normal', 'Producto con stock dentro de los niveles esperados.', true, true, 1),
  ('Bajo', 'Producto con stock por debajo del minimo.', true, true, 2),
  ('Critico', 'Producto con stock en nivel critico.', true, true, 3)
on conflict (nombre) do update
  set descripcion = excluded.descripcion,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

select public.registrar_estructura_catalogos(
  'estado_producto',
  'Estados de Producto',
  'Inventarios',
  'Catalogo de estados de disponibilidad de un producto',
  true,
  '{"id":"Identificador unico del estado de producto.","nombre":"Nombre del estado de producto.","descripcion":"Descripcion funcional del estado de producto.","activo":"Indica si el estado esta disponible para uso.","es_sistema":"Indica si el registro pertenece a la configuracion base.","orden":"Orden de visualizacion del estado.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','nombre']::text[]
);
