-- Modulo de compras: proveedores y ordenes de compra.
-- Cierra el ciclo de inventario (las entradas se originan en compras a proveedores).
-- Idempotente: se puede ejecutar cuantas veces se necesite.

-- ============ 1. proveedor ============
create table if not exists public.proveedor (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  nit text,
  contacto text,
  telefono text,
  correo text,
  direccion text,
  departamento_id bigint references public.departamento(id),
  municipio_id bigint references public.municipio(id),
  activo boolean not null default true,
  es_sistema boolean not null default false,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============ 2. orden_compra ============
create table if not exists public.orden_compra (
  id bigint generated by default as identity primary key,
  numero text not null unique,
  proveedor_id bigint not null references public.proveedor(id),
  fecha date not null default current_date,
  estado text not null default 'Pendiente',
  subtotal numeric(12,2) not null default 0,
  iva numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  usuario text,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============ 3. orden_compra_detalle ============
create table if not exists public.orden_compra_detalle (
  id bigint generated by default as identity primary key,
  orden_compra_id bigint not null references public.orden_compra(id) on delete cascade,
  producto_id bigint not null references public.producto(id),
  cantidad numeric(12,2) not null check (cantidad > 0),
  unidad_compra_id bigint references public.unidad_compra(id),
  costo_unitario numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_proveedor_activo on public.proveedor(activo);
create index if not exists idx_orden_compra_proveedor_id on public.orden_compra(proveedor_id);
create index if not exists idx_orden_compra_created_at on public.orden_compra(created_at desc);
create index if not exists idx_orden_compra_estado on public.orden_compra(estado);
create index if not exists idx_orden_compra_detalle_orden on public.orden_compra_detalle(orden_compra_id);

select public.registrar_estructura_catalogos(
  'proveedor',
  'Proveedores',
  'Compras',
  'Catalogo de proveedores que abastecen los inventarios',
  false,
  '{"id":"Identificador unico del proveedor.","codigo":"Codigo interno del proveedor.","nombre":"Nombre o razon social del proveedor.","nit":"Numero de identificacion tributaria del proveedor.","contacto":"Persona de contacto principal.","telefono":"Numero de telefono del proveedor.","correo":"Correo electronico del proveedor.","direccion":"Direccion fisica del proveedor.","departamento_id":"Departamento donde se ubica el proveedor.","municipio_id":"Municipio donde se ubica el proveedor.","activo":"Indica si el proveedor esta disponible para compras.","es_sistema":"Indica si el registro pertenece a la configuracion base.","orden":"Orden de visualizacion del proveedor.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','codigo']::text[]
);

select public.registrar_estructura_catalogos(
  'orden_compra',
  'Ordenes de Compra',
  'Compras',
  'Cabecera de las ordenes de compra a proveedores',
  false,
  '{"id":"Identificador unico de la orden de compra.","numero":"Numero correlativo de la orden de compra.","proveedor_id":"Proveedor al que se realiza la compra.","fecha":"Fecha de emision de la orden de compra.","estado":"Estado actual de la orden (Pendiente, Recibida, Anulada).","subtotal":"Subtotal de la compra.","iva":"Impuesto IVA de la compra.","total":"Total de la compra.","usuario":"Usuario que registro la orden.","notas":"Observaciones generales de la orden.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','numero']::text[]
);

select public.registrar_estructura_catalogos(
  'orden_compra_detalle',
  'Detalle de Ordenes de Compra',
  'Compras',
  'Lineas de productos de cada orden de compra',
  false,
  '{"id":"Identificador unico del detalle.","orden_compra_id":"Orden de compra a la que pertenece la linea.","producto_id":"Producto o insumo comprado.","cantidad":"Cantidad comprada.","unidad_compra_id":"Unidad de compra aplicada a la linea.","costo_unitario":"Costo unitario del producto.","total":"Total de la linea (cantidad por costo unitario).","created_at":"Fecha y hora de creacion del registro."}'::jsonb,
  array['id']::text[]
);

-- ============ 4. estado_orden_compra ============
create table if not exists public.estado_orden_compra (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.estado_orden_compra (codigo, nombre, descripcion, activo, es_sistema, orden)
values
  ('PEN', 'Pendiente', 'Orden creada, a la espera de recepcion.', true, true, 1),
  ('REC', 'Recibida', 'Orden recibida por completo.', true, true, 2),
  ('ANU', 'Anulada', 'Orden anulada.', true, true, 3)
on conflict (codigo) do update
  set nombre = excluded.nombre,
      descripcion = excluded.descripcion,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

select public.registrar_estructura_catalogos(
  'estado_orden_compra',
  'Estados de Orden de Compra',
  'Compras',
  'Catalogo de estados del ciclo de vida de una orden de compra',
  true,
  '{"id":"Identificador unico del estado de orden de compra.","codigo":"Codigo corto del estado.","nombre":"Nombre del estado de la orden de compra.","descripcion":"Descripcion funcional del estado.","activo":"Indica si el estado esta disponible para uso.","es_sistema":"Indica si el registro pertenece a la configuracion base.","orden":"Orden de visualizacion del estado.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','codigo','nombre']::text[]
);
