-- Clientes y facturacion: catalogo de clientes y cabecera de facturas.
-- Complementa el POS, que hoy guarda el cliente como texto libre.
-- Idempotente: se puede ejecutar cuantas veces se necesite.

-- ============ 1. cliente ============
create table if not exists public.cliente (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  nit text,
  telefono text,
  correo text,
  direccion text,
  departamento_id bigint references public.departamento(id),
  municipio_id bigint references public.municipio(id),
  activo boolean not null default true,
  es_sistema boolean not null default false,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============ 2. factura ============
create table if not exists public.factura (
  id bigint generated by default as identity primary key,
  numero text not null unique,
  venta_pos_id bigint references public.venta_pos(id),
  cliente_id bigint references public.cliente(id),
  fecha_emision date not null default current_date,
  subtotal numeric(12,2) not null default 0,
  iva numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  usuario text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_cliente_activo on public.cliente(activo);
create index if not exists idx_cliente_nit on public.cliente(nit);
create index if not exists idx_factura_venta_pos_id on public.factura(venta_pos_id);
create index if not exists idx_factura_cliente_id on public.factura(cliente_id);
create index if not exists idx_factura_created_at on public.factura(created_at desc);

select public.registrar_estructura_catalogos(
  'cliente',
  'Clientes',
  'Punto de Venta',
  'Catalogo de clientes del negocio',
  false,
  '{"id":"Identificador unico del cliente.","codigo":"Codigo interno del cliente.","nombre":"Nombre completo del cliente.","nit":"Numero de identificacion tributaria del cliente.","telefono":"Numero de telefono del cliente.","correo":"Correo electronico del cliente.","direccion":"Direccion del cliente.","departamento_id":"Departamento donde se ubica el cliente.","municipio_id":"Municipio donde se ubica el cliente.","activo":"Indica si el cliente esta disponible para ventas.","es_sistema":"Indica si el registro pertenece a la configuracion base.","orden":"Orden de visualizacion del cliente.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','codigo']::text[]
);

select public.registrar_estructura_catalogos(
  'factura',
  'Facturas',
  'Punto de Venta',
  'Facturas emitidas por ventas del POS',
  false,
  '{"id":"Identificador unico de la factura.","numero":"Numero de factura (serie y correlativo).","venta_pos_id":"Venta POS que origina la factura.","cliente_id":"Cliente al que se emite la factura.","fecha_emision":"Fecha de emision de la factura.","subtotal":"Subtotal facturado.","iva":"Impuesto IVA de la factura.","total":"Total de la factura.","usuario":"Usuario que emitio la factura.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','numero']::text[]
);
