-- Catalogos para des-quemar presentacion y unidad de medida de recetas.
-- Reutiliza la funcion public.registrar_estructura_catalogos definida en la 027.
-- Idempotente: se puede ejecutar cuantas veces se necesite.

-- ============ 1. catalogo_presentacion_receta ============
create table if not exists public.catalogo_presentacion_receta (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.catalogo_presentacion_receta (codigo, nombre, descripcion, activo, es_sistema, orden)
values
  ('TU', 'Tamaño Único', 'Presentacion estandar sin variantes de tamaño.', true, true, 1),
  ('P', 'Pequeño', 'Presentacion de tamaño pequeño.', true, true, 2),
  ('M', 'Mediano', 'Presentacion de tamaño mediano.', true, true, 3),
  ('G', 'Grande', 'Presentacion de tamaño grande.', true, true, 4)
on conflict (codigo) do update
  set nombre = excluded.nombre,
      descripcion = excluded.descripcion,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

select public.registrar_estructura_catalogos(
  'catalogo_presentacion_receta',
  'Presentaciones de Receta',
  'Produccion y Recetas',
  'Catalogo de presentaciones o tamaños disponibles para recetas',
  true,
  '{"id":"Identificador unico de la presentacion.","codigo":"Codigo corto de la presentacion.","nombre":"Nombre visible de la presentacion.","descripcion":"Descripcion funcional de la presentacion.","activo":"Indica si la presentacion esta disponible para uso.","es_sistema":"Indica si el registro pertenece a la configuracion base.","orden":"Orden de visualizacion de la presentacion.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','codigo','nombre']::text[]
);

-- ============ 2. unidad_medida ============
create table if not exists public.unidad_medida (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  es_sistema boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.unidad_medida (codigo, nombre, descripcion, activo, es_sistema, orden)
values
  ('GR', 'g', 'Gramo: unidad de masa del sistema metrico.', true, true, 1),
  ('ML', 'ml', 'Mililitro: unidad de volumen.', true, true, 2),
  ('LT', 'L', 'Litro: unidad de volumen.', true, true, 3),
  ('KG', 'kg', 'Kilogramo: unidad de masa.', true, true, 4),
  ('UN', 'unidad', 'Pieza individual.', true, true, 5),
  ('DOC', 'docena', 'Conjunto de doce piezas.', true, true, 6)
on conflict (codigo) do update
  set nombre = excluded.nombre,
      descripcion = excluded.descripcion,
      activo = excluded.activo,
      es_sistema = excluded.es_sistema,
      orden = excluded.orden,
      updated_at = now();

select public.registrar_estructura_catalogos(
  'unidad_medida',
  'Unidades de Medida',
  'Produccion y Recetas',
  'Catalogo de unidades de medida usadas en ingredientes de recetas',
  true,
  '{"id":"Identificador unico de la unidad de medida.","codigo":"Codigo corto de la unidad de medida.","nombre":"Simbolo o nombre de la unidad de medida.","descripcion":"Descripcion funcional de la unidad de medida.","activo":"Indica si la unidad de medida esta disponible para uso.","es_sistema":"Indica si el registro pertenece a la configuracion base.","orden":"Orden de visualizacion de la unidad de medida.","created_at":"Fecha y hora de creacion del registro.","updated_at":"Fecha y hora de ultima actualizacion del registro."}'::jsonb,
  array['id','codigo','nombre']::text[]
);
